export const LOCATIONS: Record<string, string[]> = {
	Aceh: ['Banda Aceh', 'Langsa', 'Lhokseumawe', 'Sabang', 'Subulussalam', 'Kab. Aceh Barat', 'Kab. Aceh Besar', 'Kab. Pidie'],
	'Sumatera Utara': ['Medan', 'Binjai', 'Pematangsiantar', 'Sibolga', 'Tanjungbalai', 'Tebing Tinggi', 'Kab. Asahan', 'Kab. Deli Serdang', 'Kab. Karo'],
	'Sumatera Barat': ['Padang', 'Bukittinggi', 'Pariaman', 'Padang Panjang', 'Payakumbuh', 'Sawahlunto', 'Solok', 'Kab. Agam', 'Kab. Tanah Datar'],
	Riau: ['Pekanbaru', 'Dumai', 'Kab. Bengkalis', 'Kab. Kampar', 'Kab. Siak', 'Kab. Indragiri Hilir', 'Kab. Rokan Hulu'],
	'Kepulauan Riau': ['Tanjungpinang', 'Batam', 'Kab. Bintan', 'Kab. Karimun', 'Kab. Natuna', 'Kab. Lingga'],
	Jambi: ['Jambi', 'Sungai Penuh', 'Kab. Batanghari', 'Kab. Bungo', 'Kab. Kerinci', 'Kab. Merangin'],
	'Sumatera Selatan': ['Palembang', 'Lubuklinggau', 'Pagar Alam', 'Prabumulih', 'Kab. Banyuasin', 'Kab. Lahat', 'Kab. Musi Banyuasin'],
	'Bangka Belitung': ['Pangkalpinang', 'Kab. Bangka', 'Kab. Belitung', 'Kab. Bangka Barat', 'Kab. Bangka Tengah', 'Kab. Bangka Selatan'],
	Bengkulu: ['Bengkulu', 'Kab. Bengkulu Selatan', 'Kab. Bengkulu Utara', 'Kab. Kaur', 'Kab. Seluma', 'Kab. Mukomuko'],
	Lampung: ['Bandar Lampung', 'Metro', 'Kab. Lampung Barat', 'Kab. Lampung Selatan', 'Kab. Lampung Tengah', 'Kab. Lampung Timur'],
	'DKI Jakarta': ['Jakarta Pusat', 'Jakarta Utara', 'Jakarta Barat', 'Jakarta Selatan', 'Jakarta Timur', 'Kepulauan Seribu'],
	'Jawa Barat': ['Bandung', 'Bekasi', 'Bogor', 'Cimahi', 'Cirebon', 'Depok', 'Sukabumi', 'Tasikmalaya', 'Banjar', 'Kab. Bandung', 'Kab. Bekasi', 'Kab. Bogor', 'Kab. Ciamis', 'Kab. Cianjur', 'Kab. Garut', 'Kab. Karawang'],
	Banten: ['Serang', 'Cilegon', 'Tangerang', 'Tangerang Selatan', 'Kab. Lebak', 'Kab. Pandeglang', 'Kab. Serang', 'Kab. Tangerang'],
	'Jawa Tengah': ['Semarang', 'Magelang', 'Pekalongan', 'Salatiga', 'Surakarta', 'Tegal', 'Kab. Banyumas', 'Kab. Cilacap', 'Kab. Demak', 'Kab. Jepara', 'Kab. Kudus', 'Kab. Semarang'],
	'DI Yogyakarta': ['Yogyakarta', 'Kab. Bantul', 'Kab. Gunungkidul', 'Kab. Kulon Progo', 'Kab. Sleman'],
	'Jawa Timur': ['Surabaya', 'Batu', 'Blitar', 'Kediri', 'Madiun', 'Malang', 'Mojokerto', 'Pasuruan', 'Probolinggo', 'Kab. Banyuwangi', 'Kab. Gresik', 'Kab. Jember', 'Kab. Jombang', 'Kab. Malang', 'Kab. Sidoarjo'],
	Bali: ['Denpasar', 'Kab. Badung', 'Kab. Bangli', 'Kab. Buleleng', 'Kab. Gianyar', 'Kab. Jembrana', 'Kab. Karangasem', 'Kab. Klungkung', 'Kab. Tabanan'],
	'Nusa Tenggara Barat': ['Mataram', 'Bima', 'Kab. Lombok Barat', 'Kab. Lombok Tengah', 'Kab. Lombok Timur', 'Kab. Lombok Utara', 'Kab. Sumbawa'],
	'Nusa Tenggara Timur': ['Kupang', 'Kab. Ende', 'Kab. Flores Timur', 'Kab. Manggarai', 'Kab. Ngada', 'Kab. Sikka', 'Kab. Sumba Timur'],
	'Kalimantan Barat': ['Pontianak', 'Singkawang', 'Kab. Ketapang', 'Kab. Kubu Raya', 'Kab. Sambas', 'Kab. Sanggau'],
	'Kalimantan Tengah': ['Palangka Raya', 'Kab. Barito Selatan', 'Kab. Kapuas', 'Kab. Kotawaringin Barat', 'Kab. Kotawaringin Timur'],
	'Kalimantan Selatan': ['Banjarmasin', 'Banjarbaru', 'Kab. Banjar', 'Kab. Barito Kuala', 'Kab. Kotabaru', 'Kab. Tabalong', 'Kab. Tanah Bumbu'],
	'Kalimantan Timur': ['Samarinda', 'Balikpapan', 'Bontang', 'Kab. Berau', 'Kab. Kutai Kartanegara', 'Kab. Kutai Timur', 'Kab. Penajam Paser Utara'],
	'Kalimantan Utara': ['Tarakan', 'Kab. Bulungan', 'Kab. Malinau', 'Kab. Nunukan'],
	'Sulawesi Utara': ['Manado', 'Bitung', 'Kotamobagu', 'Tomohon', 'Kab. Minahasa', 'Kab. Minahasa Selatan', 'Kab. Minahasa Utara'],
	'Sulawesi Tengah': ['Palu', 'Kab. Banggai', 'Kab. Donggala', 'Kab. Morowali', 'Kab. Poso', 'Kab. Sigi'],
	'Sulawesi Selatan': ['Makassar', 'Palopo', 'Parepare', 'Kab. Bone', 'Kab. Gowa', 'Kab. Luwu', 'Kab. Maros', 'Kab. Wajo'],
	'Sulawesi Tenggara': ['Kendari', 'Baubau', 'Kab. Buton', 'Kab. Kolaka', 'Kab. Konawe', 'Kab. Konawe Selatan'],
	Gorontalo: ['Gorontalo', 'Kab. Gorontalo', 'Kab. Gorontalo Utara', 'Kab. Bone Bolango'],
	'Sulawesi Barat': ['Mamuju', 'Kab. Majene', 'Kab. Mamasa', 'Kab. Polewali Mandar'],
	Maluku: ['Ambon', 'Tual', 'Kab. Buru', 'Kab. Maluku Tengah', 'Kab. Maluku Tenggara', 'Kab. Seram Bagian Barat'],
	'Maluku Utara': ['Ternate', 'Tidore Kepulauan', 'Kab. Halmahera Barat', 'Kab. Halmahera Selatan', 'Kab. Halmahera Utara'],
	Papua: ['Jayapura', 'Kab. Biak Numfor', 'Kab. Jayapura', 'Kab. Keerom', 'Kab. Kepulauan Yapen'],
	'Papua Barat': ['Sorong', 'Kab. Fakfak', 'Kab. Manokwari', 'Kab. Raja Ampat', 'Kab. Teluk Bintuni'],
	'Papua Tengah': ['Nabire', 'Kab. Deiyai', 'Kab. Mimika', 'Kab. Paniai', 'Kab. Puncak Jaya'],
	'Papua Pegunungan': ['Wamena', 'Kab. Jayawijaya', 'Kab. Pegunungan Bintang', 'Kab. Tolikara'],
	'Papua Selatan': ['Merauke', 'Kab. Asmat', 'Kab. Boven Digoel', 'Kab. Mappi'],
	'Papua Barat Daya': ['Sorong', 'Kab. Maybrat', 'Kab. Raja Ampat', 'Kab. Sorong Selatan', 'Kab. Tambrauw']
};

export const DISCIPLINES = [
	'Akuntansi & Pembukuan',
	'Analisis Data & Sains',
	'Arsitektur & Desain Interior',
	'Asisten Virtual & Admin',
	'Desain Busana & Tekstil',
	'Desain Grafis & Branding',
	'Desain UI/UX & Produk',
	'Dukungan IT & Infrastruktur',
	'Dukungan Pelanggan (Customer Service)',
	'E-commerce & Dropshipping',
	'Entri Data & Transkripsi',
	'Fotografi',
	'Hubungan Masyarakat (PR)',
	'Jaringan & Keamanan Siber',
	'Kesehatan & Kebugaran',
	'Keuangan & Pajak',
	'Konsultan Bisnis',
	'Layanan Hukum',
	'Manajemen Acara (Event Organizer)',
	'Manajemen Media Sosial & Komunitas',
	'Modeling 3D & CAD',
	'Pemasaran Digital & SEO',
	'Pendidikan & Bimbingan Belajar',
	'Penerjemahan & Lokalisasi',
	'Pengembang Aplikasi (Web/Mobile)',
	'Pengembangan Game',
	'Penjualan & Pengembangan Bisnis',
	'Penulisan Konten & Copywriting',
	'Pertanian & Agribisnis',
	'Produksi Audio & Musik',
	'Produksi Video & Animasi',
	'Sulih Suara (Voice Over)',
	'Sumber Daya Manusia (HR) & Rekrutmen',
	'Teknik Elektro & Robotika',
	'Teknik Mesin & Manufaktur',
	'Teknik Sipil & Konstruksi',
	'Lainnya'
];
